### ISSUE TITLE
Exception while applying ripple in removed button

### ISSUE THREAD

**Issue by bcardiff** [jamesmfriedman/rmwc#181] opened 2018-04-04 21:03 UTC
## RMWC or MDC?

I am not 100% sure.

### What RMWC Version are you using?

1.4.1

### What are the steps to reproduce the bug?

The `Fab` component applies ripple by default. If, upon click, the button is removed an exception is raised.

```
Cannot read property 'getBoundingClientRect' of null
    at Object.computeBoundingRect (https://xpzw5kolqq.codesandbox.io/node_modules/
material/ripple/dist/mdc.ripple.js:904:33
    at MDCRippleFoundation.rmBoundedActivationClasses_ (https://xpzw5kolqq.codesandbox.io/node_modules/
material/ripple/dist/mdc.ripple.js:1507:21
    at MDCRippleFoundation.runDeactivationUXLogicIfReady_ (https://xpzw5kolqq.codesandbox.io/node_modules/
material/ripple/dist/mdc.ripple.js:1490:14
    at MDCRippleFoundation._this.activationTimerCallback_ (https://xpzw5kolqq.codesandbox.io/node_modules/
material/ripple/dist/mdc.ripple.js:1154:13
    at eval (https://xpzw5kolqq.codesandbox.io/node_modules/
material/ripple/dist/mdc.ripple.js:1432:24
```

A repro sandbox can be found at https://codesandbox.io/s/xpzw5kolqq

### What is the expected behavior?

I would expect that no exception should be raised. If the button is gone, no ripple effect should be triggered.

**Comment by jamesmfriedman** [comment] 2018-04-05 02:27
Duplicate of #175 

This is an MDC bug and was just patched downstream. The fix will be picked up in the next release of RMWC.

**Closed by jamesmfriedman** 2018-04-05 02:27 UTC
