### ISSUE TITLE
Custom classNames should be appended

### ISSUE THREAD

**Issue by bcardiff** [jamesmfriedman/rmwc#163] opened 2018-03-15 17:45 UTC
I am starting to try this package to use mdc. I notice that when adding a `className` to an element like `<Fab className="my-class">favorite</Fab>`

The rendered markup is `class="my-class mdc-fab mdc-ripple-upgraded"`.
I would expect it to be `class="mdc-fab mdc-ripple-upgraded my-class "`.

This subtle difference helps overriding easily some css rules inherit from mdc (without needing to use `!important`) 

Other packages like react-md works in the same way: custom classes are appended to the framework ones.

Maybe I am missing some scenario regarding why is better to prepend the custom classes. I am happy to listen to them.

---

rmwc 1.3.0
material-components-web 0.31.0

**Comment by jamesmfriedman** [comment] 2018-03-15 18:39
duplicate of #124.

Ordering of classes in the DOM does not matter for CSS specificity. The simply need to make a more specific selector than the ones included with MDC.

**Closed** 2018-03-15 18:55 UTC
Labels: question, wontfix
