### ISSUE TITLE
IconButton: doesn't render the icon when tagging a component

### ISSUE THREAD

**Issue by c-is** [jamesmfriedman/rmwc#415] opened 2019-02-19 18:49 UTC
- What RMWC Version are you using: 5.1.6

- Name your build system: Webpack 4.27.0

- Describe the bug with as much detail as possible:
When tagging a component like `Link`, the icon doesn't show up
```javascript
<IconButton
  icon={{ icon: 'edit', size: 'medium' }} // or icon="edit"
  label="some label"
  tag={Link}
  to="/link"
/>
```
The rendered element now has got 
`<a icon="[object Object]">` without an icon
and if I set the icon like `icon="edit"`, the element will be
`<a icon="edit">`  also without an icon

if I replace `IconButton` to  `Icon` (@rmwc/icon) or `<Button>`, it works fine with the tagged element.

----
I'm not sure if it's a bug or not implemented, but please let me know about your thoughts.
Thank you in advance!

**Comment by jamesmfriedman** [comment] 2019-02-19 20:11
Definitely a regression, I'll look into why this is happening

**Comment by jamesmfriedman** [comment] 2019-02-20 03:24
Thanks for reporting this. Was a pretty simple fix, but I was able to clean up the logic of how tag works after this bug made me realize there were really only two code paths.

Being published as we speak, fixed with 5.1.7

Follow up question, for me the `tag` functionality is one of the differentiating factors in this library. Do you use it often? Do you like the way it works (when it works ;).

**Closed** 2019-02-20 03:27 UTC

**Comment by c-is** [comment] 2019-02-20 12:45
Thanks for the quick fix! It's working great now.

I use this tag functionality quite often as I usually tag a Link component for Button or IconButton.
This package is amazing. I can modify things easily without using other modules. Thank you again.

---
By the way, unfortunately I detected another error, but **I yet cannot make sure if the problem comes from RMWC or not**, but I think it worths mentioning.

So my pages work fine without problems locally and the build process is also fine locally.
However when it's built on the staging through a deployment in Azure, the page has an error.
My team and I adjusted the environment both on local and staging, but the staging somehow doesn't work. It has been happening since I upgraded RMWC from 4.0.6 to 5x and if I remove `import { Button } from '@rmwc/button';` (more precisely, the import from `@rmwc`  ) for example, the pages start working again.

### The staging environment

- RMWC version: 5.x.x (I tested with 5.1.6 and 5.1.7)
- Node version: 10.15.1
- NPM version: 6.5.0
- user agent: npm/6.5.0 node/v10.15.1 win32 x64
- Agent Pool: Hosted VS2017
- How I use React: only client side

### Screenshots
screenshot of the console error
<img width="1278" alt="screenshot 2019-02-20 at 11 21 13" src="https://user-images.githubusercontent.com/22959908/53092251-8e07ba80-3514-11e9-920a-35656efb27c5.png">

screenshot of the error code on staging
<img width="876" alt="screenshot 2019-02-20 at 13 33 53" src="https://user-images.githubusercontent.com/22959908/53092225-80523500-3514-11e9-9cf6-537e12ff620e.png">

screenshot of the same code in the local environment without errors
<img width="664" alt="screenshot 2019-02-19 at 18 04 15" src="https://user-images.githubusercontent.com/22959908/53092170-51d45a00-3514-11e9-8f0f-b0361aa87d76.png">

---
I assume it comes from "Ripple" of Material Component which comes along with RMWC, but as I said before, we cannot make sure the problem is related to RMWC since the codes on the staging and local seem to be a tad different, but it's been happening since I upgraded the version RMWC. Do you have any ideas what causing this problem? Thank you.

**Comment by jamesmfriedman** [comment] 2019-02-20 14:03
I have lots of ideas. This is related by RMWC, but likely caused by your build / build system.

Thoughts
- What build system are you using?
- RMWC 5 now uses Typescript for its build, so it is in a different format than V4
- RMWC 5 now includes a modules format for tree shaking. If you build system is using tree shaking (Webpack 4, Rollup), it looks like it might be removing something it shouldn't be
- Less likely, a minification error, but still possible
- Typescript transpiles with helpers available in every file (think built in polyfills). It is possible these are getting removed during minification
- My last guess is `useBuiltIns: false` in your babel config. This very well may be removing any polyfills that are present. https://babeljs.io/docs/en/babel-preset-env#usebuiltins-false
- I double checked both the dist and next built files, the line in question pre-minified looks like this:
`var WithRippleComponent = withProviderContext()(React.forwardRef(function (_a, ref) {`
Just calling that out because something about your Build is wrapping withProviderContext in Object

Ideas for troubleshooting
- Turn off minification to see if that corrects the issue (obviously turn it back on after, but see if it causes the problem)
- If using Webpack / Rollup, see if you can disable tree shaking. For webpack, I believe you can add "sideEffects: true" in package.json to disable it.
- Check that babelConfig entry
- Do a diff between your dev and staging config to see what pieces might be adding to the issue
- remove node_modules and reinstall

Not likely a bug in RMWC itself, but of course happy to fix something if the issue does end up being the library.

**Comment by c-is** [comment] 2019-02-26 13:46
Sorry for the delay, we've finally sorted out the problem.

The issue was that we had mixed several individual v4.x packages among the core RMWC@5.x
We'd had modules as below:
@rmwc/top-app-bar 4.0.1
rmwc 5.1.7

Since I removed top-app-bar 4.0.1 and reinstalled the entire rmwc@5.1.7 package, it's been working fine.
I followed your step one by one and it was indeed very helpful. Thank you so much for your generous support.

**Comment by jamesmfriedman** [comment] 2019-02-26 13:48
Hey no problem, glad you were able to work it out. Generally speaking different versions of RMWC will be fine to use together, the jump from 4 to 5 is definitely an exception because of the rewrite. Come version 6, you should be able to have multiple version and upgrade independently without issue.
