### ISSUE TITLE
Material Icons launch tap to search on chrome android

### ISSUE THREAD

**Issue by sNohz** [jamesmfriedman/rmwc#263] opened 2018-07-07 19:46 UTC
Chrome on android interprets material icons as text and launches "tap to search"

### What RMWC Version are you using?

1.7.6

### What browser(s) and React Version is this bug affecting?

Chrome on Android

Mozilla/5.0 (Linux; Android 8.1.0; ONEPLUS A5010 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

### What build system are you using?

Create React App

### What are the steps to reproduce the bug?

Go on the RMWC Website and Click the menu Icon

### What is the expected behavior?

Open the drawer

### What is the actual behavior?

Open the drawer but launch "tap to Search" bar at the bottom of the screen

### Any other information you believe would be useful?

Icons are loaded by font API in my project

**Comment by jamesmfriedman** [comment] 2018-07-10 21:58
Duplicate of https://github.com/jamesmfriedman/rmwc/issues/160. Please see that issue for the answer.

Basically, you can either change the tag, or use some global CSS to set pointer events to null on icons. Thats out of scope for RMWC, but feel free to report the issue to MDC.

**Closed by jamesmfriedman** 2018-07-10 21:58 UTC
