### ISSUE TITLE
Enhanced Select is not opening

### ISSUE THREAD

**Issue by Brunezkey** [jamesmfriedman/rmwc#481] opened 2019-08-21 21:33 UTC
Hello everyone, again thanks for the awesome work! Looks great.

I'm facing an issue though:
If you go to the documentation page and look for the Enhanced Select component, you'll instantly notice that it will open for less than a second and then close instantly. This is not supposed to happen.

Docs page: [Select menus](https://rmwc.io/select-menus)
Actually I noticed this issue is happening when I'm using the trackpad to open the select menu. 

Can you guys fix it? Thanks in advance.

**Comment by jamesmfriedman** [comment] 2019-08-22 00:25
Thanks for reporting. This is definitely a regression caused by an update to material web components. 

For the time being you can downgrade to the previous minor version of the select, but I’ll definitely prioritize getting this fixed.

**Comment by jamesmfriedman** [comment] 2019-09-10 00:38
I can confirm this was an issue with MDC and was fixed by just bumping the dependencies. Will be fixed with the next release.

**Comment by jamesmfriedman** [comment] 2019-09-11 21:21
Released with 5.7.0

**Comment by robcaldecottvelo** [comment] 2019-09-13 08:54
This is not working on mobile @jamesmfriedman : navigate to the RMWC site using Chrome on Android and you cannot open an enhanced `Select`.

**Comment by jamesmfriedman** [comment] 2019-09-30 12:47
This was fixed in 5.7.1

**Closed by jamesmfriedman** 2019-09-30 12:47 UTC
Labels: Fixed in Upcoming Release
