### ISSUE TITLE
Enhanced select menus are not correctly themed in RMWC 5.7.1

### ISSUE THREAD

**Issue by MiK546** [jamesmfriedman/rmwc#498] opened 2019-10-07 12:50 UTC
I have a common ThemeProvider component as a parent of my application that provides the colour theme for the whole application. When using enhanced select menus in the latest RMWC the popup menu elements are created as children of the body element of the page. That means they are not children of the ThemeProvider component and use the default purple colour variables.

Would it be possible to instead create the enhanced select menus as children of the select elements themselves, or something similar? This would make the enhanced menus respect the same theming as their parent select element.

**Comment by jamesmfriedman** [comment] 2019-10-07 13:21
This is an interesting issue caused by the fact that it hoists itself to the body of the the document to get around any overflow issues. I’ll have to think on this one. Ideally it would just work out if the box.

**Comment by jamesmfriedman** [comment] 2020-03-21 01:34
This is technically fixed by #561 since by default the menu no longer hoists, but going to make sure it does work with hoistToBody as well

**Comment by jamesmfriedman** [comment] 2020-03-24 15:06
@MiK546 long time coming, but fixed in the upcoming release. Instead of using Google's `hoistToBody` functionality, RMWC now uses proper react portals. As long as you include the Portal inside of your ThemeProvider, everything else should work as you'd expect.

Dropping in the next release.
https://github.com/jamesmfriedman/rmwc/pull/513/commits/05129ad58fb15f079849e2f02c59c28a0da21a70

**Comment by jamesmfriedman** [comment] 2020-03-28 06:42
Fixed in 6.0.0.

**Closed by jamesmfriedman** 2020-03-28 06:42 UTC
Labels: Fixed in Upcoming Release, bug
