### ISSUE TITLE
Closing drawers is broken on Iphone/Safari browsers

### ISSUE THREAD

**Issue by ylin6** [jamesmfriedman/rmwc#133] opened 2018-01-28 01:10 UTC
### What RMWC Version are you using?

> 1.1.0
### What browser(s) and React Version is this bug affecting?

> Iphone Safari: 
 Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C202 Safari/604.1

> React 16.2

### What build system are you using?

> Webpack
### What are the steps to reproduce the bug?

> Open temporary drawer on iphone,
> try to close the drawer

### What is the expected behavior?

> Drawer close animation is smooth

### What is the actual behavior?

> Animation is very choppy/laggy. Takes > 10 seconds to close the drawer.

### Any other information you believe would be useful?

> Checked on google's website on Iphone. Seeme to work fine.

**Comment by jamesmfriedman** [comment] 2018-01-28 01:29
This is a documented bug in the MDC tracker and present on the demo page. It's can related and not one that can be fixed in RMWC. https://material-components-web.appspot.com/drawer/temporary-drawer.html

**Closed by jamesmfriedman** 2018-01-28 01:29 UTC

**Comment by izakfilmalter** [comment] 2018-01-28 11:38
@ylin6 Here is the bug on MDC so you can track it's progress and try one of the workarounds. https://github.com/material-components/material-components-web/issues/1700

**Comment by jamesmfriedman** [comment] 2018-01-28 14:11
Thanks for posting that Izak, that would be been helpful :). 

Just found out the issue is resolved with ios 11.2.5

**Comment by ylin6** [comment] 2018-01-29 14:50
Thank you guys! @jamesmfriedman @izakfilmalter
