### ISSUE TITLE
RMWC forces double inclusion of React packages

### ISSUE THREAD

**Issue by mutsys** [jamesmfriedman/rmwc#262] opened 2018-07-07 00:19 UTC
## RMWC or MDC?

Definitely RMWC as you can see from this bundle analysis. I am loading React in my vendor bundle and then RMWC is loading it again.

![screen shot 2018-07-06 at 4 29 04 pm](https://user-images.githubusercontent.com/8465576/42404320-db521326-813c-11e8-9355-79e1645663e8.png)

I definitely did not have this issue when I was using v1.7.1 with the typings from `rmwc-typed`. I cropped up now when I switched to v1.7.6. Actually, now that I think about it, I recall `rmwc-typed` caused a similar problem and I fixed that along with a bunch of other cleanup in https://github.com/ncknt/rmwc-typed/pull/9. 

### What RMWC Version are you using?

v1.7.6

### What browser(s) and React Version is this bug affecting?

issue is independent of browser or React versions

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

Create a project using RMWC, Typescript and Webpack.
Place React in a vendor bundle separate from the main/entry bundle in `webpack.config.js`
Run a production build that includes dead code removal, minimization, etc..
Generate a bundle analysis report
See that the React libraries are included twice. Once in the vendor bundle and again in the main/entry bundle by RMWC.

### What is the expected behavior?

The React libraries should only be included once in the vendor bundle.

### What is the actual behavior?

The React libraries are included a second time in the main/entry bundle.

### Any other information you believe would be useful?

nada

**Comment by jamesmfriedman** [comment] 2018-07-07 02:09
Does dead code removal take into account different entry points? React has to be in scope for any React components to be written, but RMWC only specifies it as a peer dependency and doesn’t install it. 

I know the common chunks plugin takes care of this issue. Another option I’d think would be to add RMWC to your vendors. 

I’d be curious to know if this is an issue specific to RMWC. My

**Comment by jamesmfriedman** [comment] 2018-07-07 11:21
Here is a thread related to your issue. Webpack doesn’t automatically dedupe files across entry points. https://github.com/webpack/webpack.js.org/issues/1333

**Comment by mutsys** [comment] 2018-07-10 13:54
I am reasonably well versed in webpack configuration and am currently splitting code and generating bundles for my entry point (a single entry point), vendor bundle, async bundles for pages that may be reached from the entry point and a common bundle that contains the code shared by the async bundles. This configuration is one that I have used in a number of prior projects without issue, performing HMR in my dev server and producing bundles for production as expected. Using v1.7.1 with the type definitions from `rmwc-typed` was working well and no extraneous packages were finding their way into my bundles. This double inclusion only took place after I upgraded to v1.7.6 with its generated type definitions. I made no other changes to my project other than the `rmwc` version when this happened.

**Comment by jamesmfriedman** [comment] 2018-07-10 14:22
Thanks for the clarification on that!

Any ideas on this? It doesn't make any sense to me why the addition of types would add extra included runtime dependencies when splitting into a vendor bundle. 

I just looked at the linked issue you reported. Could it be as simple as removing the root index.d.ts file that exists for the whole project?

**Comment by mutsys** [comment] 2018-07-10 15:36
No problem, sorry it wasn't clear from my initial comment.

I will go back and retrace my steps and figure out what it was that I tweaked in `rmwc-typed`. Off the top of my head, I think it was the "export everything from every module in the package by default" that was at issue. In this case, it would be `src/rmwc.js`. If you take a look at what that actually gets transpiled into in `index.js`, you can see that touching this file in any way will result in every module of `rmwc` getting `require`d and their exports bound to this "master" module's exports. This sort of thing appears to prevent any "tree-shaking" from determining whether or not any of those package's modules are actually used. I think your intuition on the root `index.d.ts` file is on target. It contains the same troubling re-exports as `src/rmwc.js`.

And now that I am looking at my local `rmwc-typed` repo, I can see that it too at one time had the same contents in its root `index.d.ts` as does `rmwc` now. In my local repo, at least, the entire contents are now commented out. I'm not sure if that actually solves anything or is just the remnant of some experiment I performed to try and figure out the root cause.

I'll try some experiments later on this week and see if I can figure it out.

**Comment by jamesmfriedman** [comment] 2018-07-10 22:01
@mutsys you seem to be wicked smart and well versed in Typescript (which is currently a weak area of mine). Would you have time to do some screen sharing and hack on some stuff with me?

I hear your comments about the auto-genning  of TypeScript not currently being ideal. The thing is, it gets us from nothing to almost everything very quickly and the types would stay in sync with every release. If it's possible (which I still think it is), I'd love to see if we can fix whats there and get TypeScript out of the beta status.

Just a friendly offer, I appreciate all of your feedback. Ping me on gitter if you're interested.

**Comment by mutsys** [comment] 2018-07-11 19:34
@jamesmfriedman pinged you on Gitter. I have some time to investigate this issue today. I'll add to this thread once I make some progress.

**Comment by jamesmfriedman** [comment] 2018-07-19 14:35
@mutsys closing this out since you confirmed on Gitter this is no longer an issue. Not sure what fixed it, but maybe you can elaborate on your findings. Thanks for reporting.

**Closed by jamesmfriedman** 2018-07-19 14:35 UTC
