### ISSUE TITLE
TextField ripple console warnings

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#413] opened 2019-02-15 16:01 UTC
RMWC 5.1.x

Occasionally we are seeing a console warning when using a `TextField`. It looks ripple related and can be worked around by passing `rootProps:{{ ripple: false }}`.

Here is the stack trace:

```bash
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `type` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
warningWithoutStack @ react-dom.development.js:506
warn @ react-dom.development.js:1634
get @ react-dom.development.js:1628
activate_ @ mdc.ripple.js:1411
activate @ mdc.ripple.js:1482
push.../../node_modules/@rmwc/ripple/dist/index.js.Ripple.activateRipple @ index.js:155
push.../../node_modules/@rmwc/ripple/dist/index.js.Ripple.handleKeyDown @ index.js:146
```

**Comment by jamesmfriedman** [comment] 2019-02-15 17:11
In the code, the event is persisted, so this is strange that you would ever see this. I made a tweak to the ripple to also persist through the deactivate event. Let me know if your'e able to repro this.

**Comment by jamesmfriedman** [comment] 2019-02-26 13:33
@robcaldecottvelo were you ever able to reproduce this?

**Comment by robcaldecottvelo** [comment] 2019-02-26 17:24
I have not tried since but I will make a concerted effort.

**Comment by jamesmfriedman** [comment] 2019-03-08 01:19
Going to close this out since it seems to have been an isolated issue. Reopen if you are able to repro.

**Closed by jamesmfriedman** 2019-03-08 01:19 UTC
