### ISSUE TITLE
Clicking outside the drawer to close it doesn't remove the mdc-dialog-scroll-lock class from the body, making it impossible to scroll after using the drawer.

### ISSUE THREAD

**Issue by rasikalele** [jamesmfriedman/rmwc#360] opened 2018-11-08 19:10 UTC
Clicking outside the drawer to close it doesn't remove the mdc-dialog-scroll-lock class from the body, making it impossible to scroll after using the drawer.
App details:
react app with create-react-app , "rmwc": "^3.0.5",

Thanks,
Rasika

**Comment by jamesmfriedman** [comment] 2018-11-09 21:44
@rasikalele I'm going to need more information to help out. A repro case using the code sandbox would be extremely helpful.

- You said clicking outside of the `drawer` doesn't remove the `mdc-dialog` class from the body. The drawers and dialogs are unrelated
- I checked that closing the dialog does properly remove the class
- I also checked that opening the drawer does not add the dialog class

**Comment by danielmahon** [comment] 2018-11-15 22:11
@jamesmfriedman I'm running into something similar all of a sudden with trying to switch between a `modal` and `dismissible` drawer (like you do on the docs site). When the modal closes from a scrim touch, these classes remain on the drawer: `mdc-drawer mdc-drawer--modal mdc-drawer--open mdc-drawer--animate mdc-drawer--closing mdc-drawer--opening`. My current solution is to turn it back into a `dismissible` drawer when closed.

**Comment by jamesmfriedman** [comment] 2018-11-15 22:31
That is a bit more descriptive. I’ll look into it.

**Comment by danielmahon** [comment] 2018-11-15 22:39
@jamesmfriedman I would have to strip/refactor a bunch of stuff to push to codesandbox but I can do that if you can't reproduce easily. I'm currently using `apollo-link-state` to manage the drawer state, I thought that maybe it was re-rendering mid-transition and that was messing up whatever was looking for the "closed" event to remove those classes, but the render order seems OK. FYI, I don't get this problem if I move the scrim and trigger the `modal` close via a nav button, seems to only happen when clicking/touching the scrim.

**Comment by jamesmfriedman** [comment] 2018-11-15 22:50
I’ve been doing some major refactors under the hood whenever these sync issues pop up that usually solves these types of problems. It’s just a different implementation path. I’ll see what the short and the long term fix is.

**Comment by jamesmfriedman** [comment] 2019-02-03 13:52
Unable to reproduce. Please re-open if you re-encounter this issue

**Closed by jamesmfriedman** 2019-02-03 13:52 UTC
Labels: unverified
