### ISSUE TITLE
[TypeScript] Compilation failure when allowSyntheticDefaultImports is false

### ISSUE THREAD

**Issue by majames** [jamesmfriedman/rmwc#465] opened 2019-05-22 06:30 UTC
What RMWC Version are you using [major.minor.patch]: `5.5.1`

Name your build system [Webpack, Rollup...]: Webpack 4, TypeScript `3.4.5`

When attempting to compile the latest version of RMWC we receive the following errors in our TypeScript project. This is because `allowSyntheticDefaultImports` is `false` in our project.

```
yarn run v1.13.0
$ yarn workspaces run build-tsc
$ tsc --build
../../../node_modules/@rmwc/dialog/dist/dialog-queue.d.ts:1:8 - error TS1192: Module '"/git/kaggleazure/node_modules/@types/react/index"' has no default export.

1 import React from 'react';
         ~~~~~

../../../node_modules/@rmwc/snackbar/dist/snackbar-queue.d.ts:1:8 - error TS1192: Module '"/git/kaggleazure/node_modules/@types/react/index"' has no default export.

1 import React from 'react';
         ~~~~~
```

The easiest solution is to change the `React` import to `import * as React from 'react';`

**Comment by jamesmfriedman** [comment] 2019-05-22 14:47
I'm not opposed to making this change for you since it would be consistent with most of the other imports, but I did some digging.

React absolutely does have a real default export, non synthetic. There are a few examples.

This is present in the main index, both defult exports
```javascript
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

And this is present at the bottom of react.development.js
```
`module.exports = react;`
```

Both of those are real default exports, not synthetic ones, so it makes me wonder what other issue you might be having.

**Comment by jamesmfriedman** [comment] 2019-05-22 15:15
Fixed with 5.5.2

**Comment by majames** [comment] 2019-05-22 23:36
That is because TypeScript **doesn't** consider the code snippet you posted above to contain a default export...

> In general, TypeScript’s view of CommonJS (and AMD) modules is that namespace imports always correspond to the shape of a CommonJS module object, and that a default import just corresponds to a member on that module named default. 

https://devblogs.microsoft.com/typescript/announcing-typescript-2-7/#easier-ecmascript-module-interoperability

**Comment by jamesmfriedman** [comment] 2019-05-23 00:54
Out of curiousity, why do you have allowSyntheticDefaultImports disabled? Also, is your issue fixed?

**Comment by majames** [comment] 2019-05-23 01:54
Legacy reasons, I'd love to enable it but the current web app I'm working on breaks when I do and that's a deep rabbit hole we don't have time to invest in at the moment 🙂 🐰

**Comment by jamesmfriedman** [comment] 2019-05-23 01:55
Well, hopefully this helps for now then

**Comment by majames** [comment] 2019-05-23 01:57
It certainly does, thanks!

**Closed** 2019-05-23 02:47 UTC

**Comment by 101arrowz** [comment] 2020-12-16 01:06
This is a regression as of v6.0.0... @jamesmfriedman could you re-apply the patch? Thanks for supporting the library for so many years, by the way; it's been my go-to for many months now.
