### ISSUE TITLE
Input label is always purple on focus despite custom theme

### ISSUE THREAD

**Issue by maarten00** [jamesmfriedman/rmwc#423] opened 2019-02-23 15:50 UTC
Here is my sandbox: https://codesandbox.io/s/k9n4p8p1l5

- What RMWC Version are you using [major.minor.patch]:5.1.8

- Name your build system [Webpack, Rollup...]:Laravel Mix with Webpack

- Describe the bug with as much detail as possible:
I have created a custom theme based on Fortnightly, but with yellow as secondary instead of purple. 
My input labels do not seem to respect the theme.

- What happened, and what was supposed to happen:
When focussing the input field, the label is purple instead of yellow.

**Comment by jamesmfriedman** [comment] 2019-02-23 16:26
This is a duplicate of #276. This is a well known problem with MDC, I’ve opened multiple issues about it. My recommendation is using some global CSS to correct the label style to the appropriate color.

**Comment by jamesmfriedman** [comment] 2019-02-23 16:37
Going to close this out since the other ticket contains an example of the workaround.

**Closed by jamesmfriedman** 2019-02-23 16:37 UTC
